import React, { useState, useEffect } from 'react';
import {
  Book,
  AlertCircle,
  CheckCircle,
  Code,
  Download,
  Copy
} from 'lucide-react';

import { apiService } from './services/api';

function App() {
  const [question, setQuestion] = useState<string>('');
  const [answer, setAnswer] = useState<string>('');
  const [ankiCode, setAnkiCode] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  // 健康检查
  useEffect(() => {
    const checkHealth = async () => {
      try {
        const response = await apiService.healthCheck();
        if (!response.success) {
          setError('后端服务不可用，请检查服务器状态');
        } else {
          setError(null);
        }
      } catch (err) {
        setError('无法连接到后端服务，请确保服务器正在运行');
      }
    };

    checkHealth();
  }, []);

  const generateAnkiCode = (front: string, back: string) => {
    return `// Anki Card Format
// Front (问题):
${front}

// Back (答案):
${back}

// Anki导入格式:
Front: ${front}
Back: ${back}
Tags: AutoGenerated
Deck: Default`;
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!question.trim()) {
      setError('请输入问题');
      return;
    }

    try {
      setIsLoading(true);
      setError(null);

      const response = await apiService.generateCard({
        question: question.trim(),
        cardType: 'basic',
        deckName: 'Default',
        tags: [],
      });

      if (response.success && response.data) {
        setAnswer(response.data.back);
        setAnkiCode(generateAnkiCode(response.data.front, response.data.back));
      } else {
        throw new Error(response.error || '生成失败');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : '生成失败');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(ankiCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      setError('复制失败');
    }
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([ankiCode], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `anki_card_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* 顶部导航 */}
      <header className="bg-white/80 backdrop-blur-sm shadow-sm border-b border-gray-100 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-center items-center py-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-blue-600 to-purple-600 rounded-xl shadow-lg">
                <Book className="w-6 h-6 text-white" />
              </div>
              <h1 className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">
                Anki卡片生成器
              </h1>
            </div>
          </div>
        </div>
      </header>

      {/* 主要内容 */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8">
          {/* 左侧：输入表单区域 */}
          <div className="lg:col-span-5 space-y-6">
            <form onSubmit={handleGenerate} className="bg-white rounded-2xl shadow-xl border border-gray-100 p-6 lg:p-8 transition-all duration-300 hover:shadow-2xl">
              <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <Book className="w-5 h-5 text-blue-600" />
                </div>
                <h2 className="text-2xl font-bold text-gray-900">创建学习卡片</h2>
              </div>

              {/* 问题输入 */}
              <div className="mb-8">
                <label className="block text-sm font-semibold text-gray-700 mb-3">
                  输入问题 <span className="text-red-500 ml-1">*</span>
                </label>
                <textarea
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  className="w-full px-4 py-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 resize-none hover:border-gray-300 text-gray-800 placeholder-gray-400"
                  placeholder="输入你想要学习的问题..."
                  rows={5}
                  disabled={isLoading}
                />
                <div className="mt-2 flex justify-between items-center">
                  <p className="text-xs text-gray-500">
                    提示：清晰的问题有助于生成更好的答案
                  </p>
                  <span className="text-xs text-gray-400">
                    {question.length}/1000
                  </span>
                </div>
              </div>

              {/* 提交按钮 */}
              <button
                type="submit"
                className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-6 rounded-xl hover:from-blue-700 hover:to-purple-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3 font-semibold text-lg transition-all duration-200 transform hover:scale-[1.02] disabled:hover:scale-100"
                disabled={isLoading || !question.trim()}
              >
                {isLoading ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    正在生成卡片...
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    生成智能卡片
                  </>
                )}
              </button>
            </form>

            {/* 答案预览 */}
            {answer && (
              <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-6 lg:p-8 animate-fade-in">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 bg-green-100 rounded-lg">
                    <CheckCircle className="w-5 h-5 text-green-600" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900">生成的答案</h2>
                </div>
                <div className="p-6 bg-gradient-to-br from-gray-50 to-blue-50 rounded-xl border border-gray-100">
                  <p className="text-gray-800 whitespace-pre-wrap leading-relaxed text-lg">{answer}</p>
                </div>
              </div>
            )}
          </div>

          {/* 右侧：Anki代码输出 */}
          <div className="lg:col-span-7">
            <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-6 lg:p-8 sticky top-24 min-h-[650px] flex flex-col">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-bold text-gray-900 flex items-center gap-3">
                  <div className="p-2.5 bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl shadow-lg">
                    <Code className="w-5 h-5 text-white" />
                  </div>
                  Anki 导出代码
                </h2>
                {ankiCode && (
                  <div className="flex gap-2">
                    <button
                      onClick={handleCopy}
                      className="p-2.5 text-gray-600 hover:text-white hover:bg-gradient-to-r hover:from-blue-500 hover:to-purple-500 rounded-xl transition-all duration-200 group shadow-sm"
                      title="复制代码"
                    >
                      {copied ? (
                        <CheckCircle className="w-5 h-5 text-green-600" />
                      ) : (
                        <Copy className="w-5 h-5 group-hover:scale-110 transition-transform" />
                      )}
                    </button>
                    <button
                      onClick={handleDownload}
                      className="p-2.5 text-gray-600 hover:text-white hover:bg-gradient-to-r hover:from-blue-500 hover:to-purple-500 rounded-xl transition-all duration-200 group shadow-sm"
                      title="下载文件"
                    >
                      <Download className="w-5 h-5 group-hover:scale-110 transition-transform" />
                    </button>
                  </div>
                )}
              </div>

              <div className="flex-1 flex flex-col">
                {ankiCode ? (
                  <div className="relative flex-1 flex flex-col">
                    <div className="absolute inset-0 bg-gradient-to-br from-blue-600/5 to-purple-600/5 rounded-xl"></div>
                    <div className="relative flex-1 p-3 lg:p-4 overflow-hidden">
                      <div className="h-full overflow-auto rounded-xl">
                        <pre className="bg-gray-900 text-gray-100 p-6 lg:p-8 rounded-xl text-sm leading-relaxed whitespace-pre-wrap break-words">
                          <code className="font-mono block">{ankiCode}</code>
                        </pre>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex-1 flex items-center justify-center">
                    <div className="text-center">
                      <div className="p-6 bg-gray-100 rounded-full w-24 h-24 mx-auto mb-6 flex items-center justify-center">
                        <div className="p-3 bg-gray-200 rounded-full">
                          <Code className="w-10 h-10 text-gray-400" />
                        </div>
                      </div>
                      <p className="text-gray-600 text-lg font-medium mb-2">准备导出</p>
                      <p className="text-gray-400 text-base">输入问题并生成卡片后</p>
                      <p className="text-gray-400 text-sm mt-1">Anki格式代码将显示在这里</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* 错误提示 */}
      {error && (
        <div className="fixed bottom-6 right-6 max-w-md bg-white border border-red-200 rounded-2xl p-5 shadow-2xl animate-fade-in z-50">
          <div className="flex items-start gap-4">
            <div className="p-2 bg-red-100 rounded-full flex-shrink-0">
              <AlertCircle className="w-5 h-5 text-red-600" />
            </div>
            <div className="flex-1">
              <div className="text-sm font-semibold text-red-900">出错了</div>
              <div className="text-sm text-red-700 mt-1 leading-relaxed">{error}</div>
            </div>
            <button
              onClick={() => setError(null)}
              className="p-1 hover:bg-red-50 rounded-lg transition-colors group"
            >
              <svg className="w-5 h-5 text-red-400 group-hover:text-red-600 transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      )}

      {/* 成功提示 */}
      {copied && (
        <div className="fixed bottom-6 left-6 bg-white border border-green-200 rounded-2xl p-5 shadow-2xl animate-fade-in z-50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-100 rounded-full">
              <CheckCircle className="w-5 h-5 text-green-600" />
            </div>
            <div className="text-sm font-semibold text-green-700">代码已成功复制到剪贴板</div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;